<h2> NUMERICAL PYTHON<h2>

In [1]:
import numpy as np

In [2]:
d=[1,3,5,7,8]

In [3]:
type(d)

list

In [4]:
np.array(d)

array([1, 3, 5, 7, 8])

In [5]:
s=np.array(d)

In [6]:
type(s)

numpy.ndarray

In [7]:
s.dtype

dtype('int32')

In [8]:
s.ndim

1

In [9]:
s.shape

(5,)

In [10]:
s.size

5

# MULTIDIMENSIONAL ARRAY
LIST OF LIST

In [11]:
c=[(2,3,4,5,6,7,8),(8,7,6,5,4,3,2),(4,5,2,3,8,7,6)]

In [12]:
c

[(2, 3, 4, 5, 6, 7, 8), (8, 7, 6, 5, 4, 3, 2), (4, 5, 2, 3, 8, 7, 6)]

In [13]:
np.array(c)

array([[2, 3, 4, 5, 6, 7, 8],
       [8, 7, 6, 5, 4, 3, 2],
       [4, 5, 2, 3, 8, 7, 6]])

In [14]:
u=np.array(c)

In [15]:
u

array([[2, 3, 4, 5, 6, 7, 8],
       [8, 7, 6, 5, 4, 3, 2],
       [4, 5, 2, 3, 8, 7, 6]])

In [16]:
u.dtype

dtype('int32')

In [17]:
u.ndim

2

In [18]:
u.shape

(3, 7)

In [19]:
u.size

21

In [20]:
u=np.array(c,dtype=np.int16)

In [21]:
u

array([[2, 3, 4, 5, 6, 7, 8],
       [8, 7, 6, 5, 4, 3, 2],
       [4, 5, 2, 3, 8, 7, 6]], dtype=int16)

In [22]:
np.array (["A","B","C",1,4,2])

array(['A', 'B', 'C', '1', '4', '2'], dtype='<U11')

In [23]:
np.array (["A","B","C"])

array(['A', 'B', 'C'], dtype='<U1')

In [24]:
np.array([1,2,3])

array([1, 2, 3])

#FUNCTIONS IN NP

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(2,14)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [27]:
np.arange(2,14,3)

array([ 2,  5,  8, 11])

In [28]:
np.arange(2,14,3,dtype=float)

array([ 2.,  5.,  8., 11.])

#lineary seperable=linspace

In [29]:
np.linspace(2,20,5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [30]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [31]:
np.linspace(2,14,3)

array([ 2.,  8., 14.])

In [32]:
np.linspace(2,8,4,dtype=np.int16)

array([2, 4, 6, 8], dtype=int16)

In [33]:
np.linspace(2,8,4,dtype=int)

array([2, 4, 6, 8])

In [34]:
np.linspace(2,8)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [38]:
np.diag([2,3,4,5,7],3)

array([[0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.diag([2,3,4,5,7],2)

array([[0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [40]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.zeros(4)

array([0., 0., 0., 0.])

In [42]:
np.full(7,9)

array([9, 9, 9, 9, 9, 9, 9])

In [43]:
np.random.rand(4)

array([0.30192831, 0.97663033, 0.75695691, 0.86228962])

#manupulation of array

In [44]:
np.linspace(2,8)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [45]:
np.linspace(2,8).shape

(50,)

In [46]:
np.linspace(2,8).reshape(2,25)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
        2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
        3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
        3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
        4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
       [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
        5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
        6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
        6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
        7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [47]:
np.linspace(2,8).reshape(2,25).shape

(2, 25)

In [48]:
np.arange(2,40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [49]:
np.arange(2,40).shape

(38,)

In [50]:
np.arange(2,40).reshape(2,19)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39]])

In [51]:
np.arange(1,37).shape

(36,)

In [52]:
np.arange(1,37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

#TRANSPOSE

In [53]:
np.transpose(np.arange(1,37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

#Stacking

In [54]:
a=np.array([1,2,3])
b=np.array([(9,7,6),(9,1,6)])
c=np.array([(9,8,12),(26,9,21)])

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([[9, 7, 6],
       [9, 1, 6]])

In [57]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 7, 6],
       [9, 1, 6]])

In [58]:
np.hstack([c,b])

array([[ 9,  8, 12,  9,  7,  6],
       [26,  9, 21,  9,  1,  6]])

#mathematical function of numpy(arithmetic operation)

In [60]:
c*b

array([[ 81,  56,  72],
       [234,   9, 126]])

In [61]:
o=np.array([1,2,3])
w=np.array([3,4,5])

In [62]:
o*w

array([ 3,  8, 15])

In [63]:
o-w

array([-2, -2, -2])

In [64]:
np.subtract(o,w)

array([-2, -2, -2])

In [65]:
o+w

array([4, 6, 8])

In [66]:
np.add(o,w)

array([4, 6, 8])

In [67]:
o/w

array([0.33333333, 0.5       , 0.6       ])

In [68]:
np.divide(o,w)

array([0.33333333, 0.5       , 0.6       ])

#np aggregrate

In [69]:
o

array([1, 2, 3])

In [70]:
o.sum()

6

In [71]:
np.transpose(np.arange(1,37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [72]:
np.transpose(np.arange(1,37).reshape(6,6)).sum(axis=0)

array([ 21,  57,  93, 129, 165, 201])

In [73]:
np.transpose(np.arange(1,37).reshape(6,6)).sum(axis=1)

array([ 96, 102, 108, 114, 120, 126])

#MEAN(min, max)

In [75]:
np.transpose(np.arange(1,37).reshape(6,6)).min(axis=0)

array([ 1,  7, 13, 19, 25, 31])

In [76]:
np.transpose(np.arange(1,37).reshape(6,6)).min(axis=1)

array([1, 2, 3, 4, 5, 6])

In [77]:
np.transpose(np.arange(1,37).reshape(6,6)).max(axis=0)

array([ 6, 12, 18, 24, 30, 36])

In [78]:
np.transpose(np.arange(1,37).reshape(6,6)).max(axis=1)

array([31, 32, 33, 34, 35, 36])

#cumulative sum

In [79]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=0)

array([[  1,   7,  13,  19,  25,  31],
       [  3,  15,  27,  39,  51,  63],
       [  6,  24,  42,  60,  78,  96],
       [ 10,  34,  58,  82, 106, 130],
       [ 15,  45,  75, 105, 135, 165],
       [ 21,  57,  93, 129, 165, 201]])

In [80]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1)

array([[  1,   8,  21,  40,  65,  96],
       [  2,  10,  24,  44,  70, 102],
       [  3,  12,  27,  48,  75, 108],
       [  4,  14,  30,  52,  80, 114],
       [  5,  16,  33,  56,  85, 120],
       [  6,  18,  36,  60,  90, 126]])

In [81]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1).sum()

1701

In [82]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1).mean(axis=0)

array([  3.5,  13. ,  28.5,  50. ,  77.5, 111. ])

In [83]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1).mean(axis=1)

array([38.5, 42. , 45.5, 49. , 52.5, 56. ])

#median

In [84]:
np.median(np.transpose(np.arange(1,37)))

18.5

#standard deviation

In [85]:
np.transpose(np.arange(1,37)).std()

10.388294694831615

In [ ]:
#for sine,cosine,tangent

In [86]:
np.sin(np.transpose(np.arange(1,37)))

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885])

#quantile

In [88]:
np.quantile(np.transpose(np.arange(1,37)).std(),0.7)

10.388294694831615